using System.Text.Json;
using System.Text.Json.Serialization;

namespace DotNetCampus.ModelContextProtocol.CompilerServices;

/// <summary>
/// 表示 MCP 工具的输入输出的 JSON Schema，由源生成器生成。<br/>
/// Represents the JSON Schema for MCP tool input and output, generated by source generator.
/// </summary>
public sealed record CompiledJsonSchema
{
    /// <summary>
    /// Schema 类型（可能是字符串或数组，数组用于表示可空类型）。<br/>
    /// 仅类型鉴别器此字段是 <see langword="null"/>，且需显式赋值。<br/>
    /// Schema type (may be a string or array, array is used to represent nullable types).<br/>
    /// Only for type discriminators, this field is <see langword="null"/> and must be explicitly assigned.
    /// </summary>
    [JsonPropertyName("type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Type { get; init; }

    /// <summary>
    /// 枚举值列表（仅用于枚举类型）。<br/>
    /// List of enumeration values (only for enum types).
    /// </summary>
    [JsonPropertyName("enum")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Enum { get; init; }

    /// <summary>
    /// 常量值（用于约束属性必须等于特定值，如多态鉴别器）。<br/>
    /// Constant value (used to constrain a property to a specific value, such as a polymorphic discriminator).
    /// </summary>
    [JsonPropertyName("const")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Const { get; init; }

    /// <summary>
    /// 枚举值的显示名称列表（与 Enum 对应，仅用于枚举类型）。<br/>
    /// List of display names for enumeration values (corresponding to Enum, only for enum types).
    /// </summary>
    [JsonPropertyName("enumNames")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? EnumNames { get; init; }

    /// <summary>
    /// 默认值（未设置默认值时需设为 <see langword="null"/>，
    /// 显式设置了默认值时必须设置值，即使值的含义为 null）。<br/>
    /// Default value (should be set to <see langword="null"/> when no default value is set,
    /// must be set when a default value is explicitly set, even if the value means null).
    /// </summary>
    [JsonPropertyName("default")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Default { get; init; }

    /// <summary>
    /// 参数描述<br/>
    /// Parameter description
    /// </summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }

    /// <summary>
    /// 对象属性定义（仅用于 object 类型）。<br/>
    /// Object property definitions (only for object type).
    /// </summary>
    [JsonPropertyName("properties")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Properties { get; init; }

    /// <summary>
    /// 必需属性列表（仅用于 object 类型）。<br/>
    /// List of required properties (only for object type).
    /// </summary>
    [JsonPropertyName("required")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<string>? Required { get; init; }

    /// <summary>
    /// 数组项类型定义（仅用于 array 类型）。<br/>
    /// Array item type definition (only for array type).
    /// </summary>
    [JsonPropertyName("items")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompiledJsonSchema? Items { get; init; }

    /// <summary>
    /// 多态类型的可能子类型列表。<br/>
    /// List of possible subtypes for polymorphic types.
    /// </summary>
    [JsonPropertyName("anyOf")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<CompiledJsonSchema>? AnyOf { get; init; }

    /// <summary>
    /// 指示对象类型是否允许额外属性（未在 properties 中定义的属性）。<br/>
    /// 当设置为 true 时，允许任意额外属性；当设置为 false 时，不允许额外属性；<br/>
    /// 当设置为 Schema 对象时，额外属性必须符合该 Schema。<br/>
    /// Indicates whether the object type allows additional properties (properties not defined in properties).<br/>
    /// When set to true, any additional properties are allowed; when set to false, no additional properties are allowed;<br/>
    /// When set to a Schema object, additional properties must conform to that Schema.
    /// </summary>
    [JsonPropertyName("additionalProperties")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? AdditionalProperties { get; init; }
}
